name: MagmaFFA
version: '1.0'
main: us.magmamc.magmaFFA.MagmaFFA
api-version: '1.21'
authors: [ MagmaMC ]
commands:
  ffa:
    description: Main command for MagmaFFA plugin
    usage: /ffa <create/setspawn/setkit/editkit/setlobby> <name>
    permission: magmaffa.player
    permission-message: You don't have permission to use this command!
  spawn:
    description: Teletransportarse al lobby principal
    usage: /spawn
    permission: magmaffa.player
permissions:
  magmaffa.admin:
    description: Allows full access to MagmaFFA commands
    default: op
  magmaffa.player:
    description: Allows use of basic MagmaFFA commands
    default: true